[package]
name = "entity"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "1.1.12" }
serde = { version = "1.0.180", features = ["derive"] }
chrono = "0.4.26"
